config/routes.rb
Rails.application.routes.draw do
  resources :cards

  resources :people

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/soul_card.rb
require 'date'

MajorArcanaCard = ["The Fool", "The magician", "The High Priestess", 	# 0 1 2
	"The Empress", "The Emperor", "The Hierophant", 				# 3 4 5
	"The Lover", "The Chariot", "Strength", 						# 6 7 8
	"The Hermit", "Wheel of Fortune", "Justice", 					# 9 10 11
	"The Hanged Man", "Death", "Temperance", 						# 12 13 14
	"The Devil", "The Tower", "The Star", 						# 15 16 17
	"The Moon", "The Sun", "Judgement", "The World"]				# 18 19 20 21
MajorArcanaPremise = ["beginnings", "active", "great balance", 
	"nature and sensation", "structure and authority", "belief system", 
	"relationship", "vigorous ego", "strength", 
	"needfinder", "turning point", "wipe the slate clean", 
	"turned upside down", "transision", "balancing", 
	"ignorance and hopelessness", "sudden change", "hope and inspiration", 
	"lost and bewildered", "enlighten", "reborn and calling", "new level"]


class MajorArcana
  attr_accessor :number, :card, :premise

  def initialize(no = 0)
    @number = no
  end

#  def number
#    @number
#  end

  def card
    MajorArcanaCard[@number]
  end

  def premise
    MajorArcanaPremise[@number]
  end
end # end of class MajorArcana

class SoulCard
  attr_accessor :date, :soul, :moon, :year

  def initialize(date = Date.new(1972, 7, 26))
    @date = date
    @soul = MajorArcana.new(soulnumber)
    @moon = MajorArcana.new(moonnumber)
    @year = MajorArcana.new
  end

  def soulnumber
    year = @date.year.to_s
    sum = year[0].to_i + year[1].to_i + year[2].to_i + year[3].to_i

    sum += self.moonnumber

    sum = sum/10 + sum%10 if sum > 9
    sum = sum              unless sum > 9

    sum
  end

  def moonnumber
    month = "%2d" % [@date.mon]
    day = "%2d" % [@date.mday]
    sum = month[0].to_i + month[1].to_i + day[0].to_i + day[1].to_i


    sum = sum/10 + sum%10 if sum > 22
    sum = 0                if sum == 22
    sum = sum              if sum < 22

    sum
  end

  def yearnumber(no)
    y = no.to_s
    sum = y[0].to_i + y[1].to_i + y[2].to_i + y[3].to_i
    sum += self.moonnumber
    if sum > 21
      sum = sum / 10 + sum % 10
    end

    @year.number = sum

    sum

  end

end

jang = SoulCard.new(Date.new(1980, 2, 19))
puts jang.date
jang.yearnumber(2014)
puts "Soul Sign : %2d %s (%s)" % [jang.soul.number, jang.soul.card, jang.soul.premise]

puts "Moon Sign : %2d %s (%s)" % [jang.moon.number, jang.moon.card, jang.moon.premise]
(1980..2014).each do |y|
  jang.yearnumber(y)
  puts "%d Year Card : %2d %s (%s)" % [y, jang.year.number, jang.year.card, jang.year.premise]
end


kim = SoulCard.new(Date.new(1972, 7, 26))
puts kim.date
kim.yearnumber(2014)
puts "Soul Sign : %2d %s (%s)" % [kim.soul.number, kim.soul.card, kim.soul.premise]
puts "Moon Sign : %2d %s (%s)" % [kim.moon.number, kim.moon.card, kim.moon.premise]
puts "Year Card : %2d %s (%s)" % [kim.year.number, kim.year.card, kim.year.premise]

(1980..2014).each do |y|
  kim.yearnumber(y)
  puts "%d Year Card : %2d %s (%s)" % [y, kim.year.number, kim.year.card, kim.year.premise]
end

app/models/year_card.rb
class YearCard < ActiveRecord::Base
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:birth, :soulcard, :sunsign, :moonsign, :minorsoulcard, :zodiaccard, :person_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :birth %><br>
    <%= f.date_select :birth, :start_year => 1900, :use_month_numbers => true %>
  </div>
  <div class="field">
    <%= f.label :soulcard %><br>
    <%= f.number_field :soulcard %>
  </div>
  <div class="field">
    <%= f.label :sunsign %><br>
    <%= f.number_field :sunsign %>
  </div>
  <div class="field">
    <%= f.label :moonsign %><br>
    <%= f.number_field :moonsign %>
  </div>
  <div class="field">
    <%= f.label :minorsoulcard %><br>
    <%= f.number_field :minorsoulcard %>
  </div>
  <div class="field">
    <%= f.label :zodiaccard %><br>
    <%= f.number_field :zodiaccard %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.text_field :person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cards</h1>

<table>
  <thead>
    <tr>
      <th>Birth</th>
      <th>Soulcard</th>
      <th>Sunsign</th>
      <th>Moonsign</th>
      <th>Minorsoulcard</th>
      <th>Zodiaccard</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.birth %></td>
        <td><%= card.soulcard %></td>
        <td><%= card.sunsign %></td>
        <td><%= card.moonsign %></td>
        <td><%= card.minorsoulcard %></td>
        <td><%= card.zodiaccard %></td>
        <td><%= card.person %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Birth:</strong>
  <%= @card.birth %>
</p>

<p>
  <strong>Soulcard:</strong>
  <%= @card.soulcard %>
</p>

<p>
  <strong>Sunsign:</strong>
  <%= @card.sunsign %>
</p>

<p>
  <strong>Moonsign:</strong>
  <%= @card.moonsign %>
</p>

<p>
  <strong>Minorsoulcard:</strong>
  <%= @card.minorsoulcard %>
</p>

<p>
  <strong>Zodiaccard:</strong>
  <%= @card.zodiaccard %>
</p>

<p>
  <strong>Person:</strong>
  <%= @card.person %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tarot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth %><br>
    <%= f.date_select :birth, :start_year => 1900, :use_month_numbers => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.birth %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @person.birth %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>